services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: shortenerdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    restart: always
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  frontend:
    build: ./frontend
    restart: always
    env_file: .env
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

volumes:
  db_data: